#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys, os, json
import logging
import argparse
import configparser

# Import requests
try:
    import requests
except ImportError:
    print("It seams `requests` is not installed. Please pip install requests")
    sys.exit(1)

# Import BeautifulSoup
try:
    from bs4 import BeautifulSoup
except ImportError:
    print("It seams `BeautifulSoup` is not installed. Please pip install beautifulsoup4")
    sys.exit(1)

# Import texttable
try:
    import texttable
except ImportError:
    print("It seams `texttable` is not installed. Please pip install texttable")
    sys.exit(1)

def configLog(debug):
    "Configure logging"
    logfile = os.path.basename(__file__) + '.log' if debug == True else None
    loglevel = logging.DEBUG if logfile is not None else None
    logging.basicConfig(format='%(asctime)s [%(module)14s][%(levelname)8s] %(message)s', filename=logfile, level=loglevel)

def printTable(list, width):
    "Print content from list to a table"
    if len(list) != 1:
        if len(list) == 2:
            print('Find 1 result\n')
        else:
            print('Find ' + str(len(list) - 1) + ' results\n')

        table = texttable.Texttable()
        table.set_cols_width(width)
        table.add_rows(list)
        print(table.draw())

    else:
        print('Nothing Found!')

def getIMDBGenre(id):
    "Fetch genre information from IMDB"
    url = "http://www.imdb.com/title/" + id
    logging.debug('imdb url:\n' + str(url))

    genres = BeautifulSoup(requests.get(url).text, "lxml").find_all('span', {'class': 'itemprop', 'itemprop': 'genre'})
    logging.debug('imdb genre:\n' + str(genres))

    return ', '.join([genre.getText() for genre in genres])

def getIMDBRating(id):
    "Fetch rating information from IMDB"
    url = "http://www.imdb.com/title/" + id
    logging.debug('imdb url:\n' + str(url))

    value = BeautifulSoup(requests.get(url).text, "lxml").find('div', {'class': 'ratingValue'})
    logging.debug('imdb rating:\n' + str(value))

    if value is not None:
        return value.strong['title'].replace('based on ', '(').replace(' user ratings', ')')
    return ""

def GET(url):
    "GET request call"
    logging.debug('url:\n' + str(url))

    response = requests.request("GET", url)
    if response.status_code != 200:
        logging.error(str(response.status_code) + ' ' + url)
        exit()

    logging.debug('response json:\n' + str(response.json()))

    return response.json()

def exit():
    "Exit!"
    logging.shutdown()
    sys.exit(1)

def main():
    # Setup parameter
    #   run script with -d, active debug mode (log file will be created)
    parser = argparse.ArgumentParser()
    parser.add_argument('searchtext', nargs='+', help='search text')
    parser.add_argument('-y', '--year',   nargs='?', help='year of release')
    parser.add_argument('-t', '--tv',   action='store_true', help='search TV show')
    parser.add_argument('-d', '--debug',  action='store_true', dest="debug", help='active debug log')
    args = parser.parse_args()

    # Configure logging
    configLog(args.debug)
    logging.debug('args:\n' + str(args))

    printResult = [['TITLE', 'DATE', 'GENRE', 'LENGTH', 'RATING', 'LINK']]
    printColWidth = [15, 10, 10, 10, 15, 40]

    # Read config.ini
    config = configparser.ConfigParser()
    config.readfp(open(os.path.dirname(__file__) + '/config.ini'))
    api_key = config['USER']['API_KEY']
    if not api_key:
        logging.critical('Empty API_KEY in config.ini')
        exit()

    # Set search url for movie or tv
    if args.tv is True:
        searchType = 'tv'
    else:
        searchType = 'movie'

    # Set search url
    url = "https://api.themoviedb.org/3/search/" + searchType + '?api_key=' + api_key + '&query=' + '%20'.join(args.searchtext)
    if args.year is not None:
        if searchType is 'tv':
            url += '&first_air_date_year=' + str(args.year)
        else:
            url += '&year=' + str(args.year)

    # Call TMDB search api to get result list
    resultList = GET(url)
    logging.debug('result list:\n' + str(resultList))

    # Search each movie/tv in list
    for item in resultList['results']:
        # Call TMDB api movie/tv api to get detail
        itemData = GET('https://api.themoviedb.org/3/' + searchType + '/' + str(item['id']) + '?api_key=' + api_key)

        imdbId = ''
        if 'imdb_id' in itemData.keys():
            imdbId = itemData['imdb_id']
        logging.debug('imdb id:\n' + str(imdbId))

        itemName = ''
        if searchType == 'movie':
            itemName = itemData['original_title']
            itemDate = itemData['release_date']
            itemTime = str(itemData['runtime'])
        else:
            itemName = itemData['original_name']
            itemDate = itemData['first_air_date']
            itemTime = str(itemData['episode_run_time'])

        itemRating = 'TMDB: ' + str(itemData['vote_average']) + '(' + str(itemData['vote_count']) + ')'
        itemLinks = 'https://www.themoviedb.org/' + searchType + '/' + str(item['id'])
        if imdbId:
            itemGenre = getIMDBGenre(imdbId)
            itemLinks += '\nhttp://www.imdb.com/title/' + imdbId
            imdbRating = getIMDBRating(imdbId)
            if imdbRating:
                itemRating += '\nIMDB: ' + imdbRating
        else:
            itemGenre = str(', '.join([g['name'] for g in itemData['genres']]))

        # Append results
        printResult.append([
            itemName,
            itemDate,
            itemGenre,
            itemTime,
            itemRating,
            itemLinks
        ])

    # Print results in terminal
    printTable(printResult, printColWidth)

if __name__ == '__main__':
    main()
